import { StyleSheet } from 'react-native';
import { Colours, Spacing, FontSize } from '../utils/constants';

const AVATAR_SIZE = 80;
const AVATAR_OFFSET = AVATAR_SIZE / 2;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colours.surface },
  centred: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: Colours.surface },

  bannerWrap: {
    position: 'relative',
    marginBottom: AVATAR_OFFSET + Spacing.sm,
  },
  banner: { height: 120, width: '100%' },
  editButton: {
    position: 'absolute',
    right: Spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: Spacing.md,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.25)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
  },
  editButtonText: { color: '#fff', fontSize: FontSize.sm, fontWeight: '800' },
  avatarWrap: {
    position: 'absolute',
    bottom: -AVATAR_OFFSET,
    left: Spacing.lg,
    width: AVATAR_SIZE,
    height: AVATAR_SIZE,
    borderRadius: AVATAR_SIZE / 2,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: Colours.surface,
  },
  avatarText: { color: '#fff', fontSize: 26, fontWeight: '900', letterSpacing: 0.5 },

  identityBlock: {
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colours.border,
    marginBottom: Spacing.sm,
  },
  name: { fontSize: FontSize.xxl, fontWeight: '900', color: Colours.text, letterSpacing: -0.5 },
  email: { fontSize: FontSize.sm, color: Colours.textSecondary, fontWeight: '600', marginTop: 2, marginBottom: Spacing.sm },
  levelBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    marginBottom: Spacing.sm,
  },
  levelBadgeText: { fontSize: FontSize.xs, fontWeight: '800', textTransform: 'capitalize' },
  metaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  infoChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: Colours.surface,
    borderWidth: 1,
    borderColor: Colours.border,
  },
  infoChipText: { fontSize: FontSize.xs, color: Colours.textSecondary, fontWeight: '700' },

  noProfileCard: {
    margin: Spacing.lg,
    backgroundColor: Colours.background,
    borderRadius: 16,
    padding: Spacing.lg,
    borderWidth: 1,
    borderColor: Colours.border,
    alignItems: 'center',
  },
  noProfileTitle: { fontSize: FontSize.lg, fontWeight: '900', color: Colours.text, marginBottom: Spacing.sm, textAlign: 'center' },
  noProfileSubtitle: { fontSize: FontSize.sm, color: Colours.textSecondary, textAlign: 'center', lineHeight: 20, fontWeight: '600', marginBottom: Spacing.lg },
  createButton: { backgroundColor: Colours.primary, borderRadius: 14, paddingHorizontal: Spacing.xl, paddingVertical: Spacing.md },
  createButtonText: { color: Colours.textLight, fontSize: FontSize.md, fontWeight: '900' },

  sectionCard: {
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.sm,
    backgroundColor: Colours.background,
    borderRadius: 16,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colours.border,
  },
  sectionTitle: { fontSize: FontSize.md, fontWeight: '900', color: Colours.text, marginBottom: Spacing.sm, letterSpacing: -0.2 },

  bio: { fontSize: FontSize.sm, color: Colours.textSecondary, lineHeight: 22, fontWeight: '600' },

  interestRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: Colours.surface,
  },
  interestLeft: { flex: 1 },
  interestName: { fontSize: FontSize.sm, fontWeight: '800', color: Colours.text },
  interestLevel: { fontSize: FontSize.xs, color: Colours.textSecondary, fontWeight: '600', marginTop: 2, textTransform: 'capitalize' },
  smallBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 999, borderWidth: 1, marginLeft: Spacing.sm },
  smallBadgeText: { fontSize: FontSize.xs, fontWeight: '800', textTransform: 'capitalize' },

  chipsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  goalChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: Colours.primaryLight,
    borderWidth: 1,
    borderColor: Colours.border,
  },
  goalChipText: { fontSize: FontSize.xs, color: Colours.primary, fontWeight: '700' },
  goalDescription: { fontSize: FontSize.sm, color: Colours.textSecondary, fontWeight: '600', lineHeight: 20, marginTop: Spacing.sm, fontStyle: 'italic' },

  prefRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: Colours.surface,
    gap: Spacing.sm,
  },
  prefIconEl: { marginTop: 2 },
  prefText: { flex: 1 },
  prefLabel: { fontSize: FontSize.xs, color: Colours.textSecondary, fontWeight: '700', marginBottom: 3 },
  prefValue: { fontSize: FontSize.sm, color: Colours.text, fontWeight: '800' },
  availChip: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: Colours.surface,
    borderWidth: 1,
    borderColor: Colours.border,
  },
  availChipText: { fontSize: FontSize.xs, color: Colours.textSecondary, fontWeight: '700' },

  explainerCard: {
    marginHorizontal: Spacing.lg,
    marginBottom: Spacing.sm,
    backgroundColor: Colours.primaryLight,
    borderRadius: 16,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colours.border,
  },
  explainerTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: Spacing.sm },
  explainerTitle: { fontSize: FontSize.sm, fontWeight: '900', color: Colours.primary },
  explainerText: { fontSize: FontSize.xs, color: Colours.text, lineHeight: 20, fontWeight: '600' },

  signOutButton: {
    marginHorizontal: Spacing.lg,
    marginTop: Spacing.lg,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colours.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: Colours.background,
  },
  signOutText: { fontSize: FontSize.sm, fontWeight: '800', color: Colours.error },
});
