import { StyleSheet } from 'react-native';
import { Colours, FontSize, Spacing } from '../utils/constants';

export const sl = StyleSheet.create({
  wrap: { marginVertical: Spacing.md },
  labels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
  },
  labelText: { fontSize: FontSize.lg, fontWeight: '900', color: Colours.primary },
  track: {
    height: 4,
    backgroundColor: Colours.border,
    borderRadius: 2,
    marginHorizontal: 12,
    position: 'relative',
  },
  trackFill: {
    position: 'absolute',
    height: 4,
    backgroundColor: Colours.primary,
    borderRadius: 2,
  },
  handle: {
    position: 'absolute',
    width: 28,
    height: 28,
    marginLeft: -14,
    top: -12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  handleInner: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: Colours.background,
    borderWidth: 2.5,
    borderColor: Colours.primary,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  ticks: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: Spacing.md,
    marginHorizontal: 12,
  },
  tickText: { fontSize: 10, color: Colours.textSecondary, fontWeight: '600' },
});

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colours.surface },

  bgBubble1: {
    position: 'absolute',
    top: -80,
    left: -70,
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: Colours.primaryLight,
    opacity: 1,
  },
  bgBubble2: {
    position: 'absolute',
    top: 300,
    right: -100,
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: Colours.primary,
    opacity: 0.12,
  },
  bgBubble3: {
    position: 'absolute',
    top: 700,
    left: -90,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: Colours.primaryLight,
    opacity: 0.9,
  },

  // No background — bubbles show through
  topBlock: {},

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.sm,
  },
  headerTitle: {
    fontSize: FontSize.xl,
    fontWeight: '900',
    color: Colours.text,
    letterSpacing: -0.4,
  },
  diceButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: Colours.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colours.border,
  },

  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.sm,
    gap: Spacing.sm,
  },
  searchBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colours.background,
    borderRadius: 14,
    paddingHorizontal: Spacing.md,
    borderWidth: 1,
    borderColor: Colours.border,
    gap: Spacing.sm,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 11,
    fontSize: FontSize.md,
    color: Colours.text,
    fontWeight: '600',
  },
  filterButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: Colours.background,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colours.border,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  filterButtonActive: {
    backgroundColor: Colours.primaryLight,
    borderColor: Colours.primary,
  },
  filterBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: Colours.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterBadgeText: { fontSize: 9, color: Colours.textLight, fontWeight: '900' },

  chipsWrapper: {
    height: 48,
  },
  chipsRow: {
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    gap: 8,
  },
  chip: {
    height: 32,
    minWidth: 56,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: Colours.background,
    borderWidth: 1,
    borderColor: Colours.border,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  chipActive: { backgroundColor: Colours.primary, borderColor: Colours.primary },
  chipText: { fontSize: FontSize.sm, fontWeight: '700', color: Colours.textSecondary },
  chipTextActive: { color: Colours.textLight },

  activeFiltersRow: {
    marginTop: 4,
  },
  activeFiltersScroll: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    gap: 8,
    alignItems: 'center',
  },
  activeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Colours.primary,
    backgroundColor: 'transparent',
  },
  activeChipText: {
    fontSize: FontSize.xs,
    color: Colours.primary,
    fontWeight: '800',
    textTransform: 'capitalize',
  },
  clearAllBtn: {
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  clearAllText: {
    fontSize: FontSize.xs,
    color: Colours.textSecondary,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },

  divider: {
    height: 1,
    backgroundColor: Colours.border,
    marginTop: Spacing.sm,
    opacity: 0.5,
  },

  listContent: {
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.xxl,
  },
  resultsCount: {
    fontSize: FontSize.sm,
    color: Colours.textSecondary,
    fontWeight: '700',
    marginBottom: Spacing.sm,
    marginTop: Spacing.xs,
  },
  cardWrap: { flex: 1, marginBottom: Spacing.sm },
  columnWrapper: { gap: Spacing.sm },

  loadingWrap: { alignItems: 'center', paddingTop: Spacing.xxl },
  loadingText: { marginTop: Spacing.sm, fontSize: FontSize.sm, color: Colours.textSecondary, fontWeight: '700' },

  emptyWrap: {
    alignItems: 'center',
    paddingTop: Spacing.xxl,
    paddingHorizontal: Spacing.xl,
  },
  emptyTitle: { fontSize: FontSize.lg, fontWeight: '900', color: Colours.text, marginBottom: Spacing.sm },
  emptySubtitle: {
    fontSize: FontSize.sm,
    color: Colours.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
    fontWeight: '600',
    marginBottom: Spacing.lg,
  },
  clearButton: {
    backgroundColor: Colours.primary,
    borderRadius: 14,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.sm,
  },
  clearButtonText: { color: Colours.textLight, fontWeight: '900', fontSize: FontSize.sm },

  joinBanner: {
    marginHorizontal: Spacing.lg,
    marginTop: Spacing.lg,
    marginBottom: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    backgroundColor: Colours.primaryLight,
    borderRadius: 18,
    padding: Spacing.md,
    borderWidth: 1.5,
    borderColor: Colours.primary + '30',
  },
  joinBannerTitle: {
    fontSize: FontSize.md,
    fontWeight: '900',
    color: Colours.text,
    marginBottom: 2,
  },
  joinBannerSub: {
    fontSize: FontSize.xs,
    color: Colours.textSecondary,
    fontWeight: '600',
  },

  modalContainer: { flex: 1, backgroundColor: Colours.background },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: Colours.border,
  },
  modalTitle: { fontSize: FontSize.xl, fontWeight: '900', color: Colours.text },
  modalClose: { fontSize: FontSize.md, color: Colours.primary, fontWeight: '900' },
  modalContent: { padding: Spacing.lg, gap: Spacing.sm },
  filterSectionTitle: {
    fontSize: FontSize.md,
    fontWeight: '800',
    color: Colours.text,
    marginTop: Spacing.md,
    marginBottom: Spacing.sm,
  },
  optionsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  optionChip: {
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: Colours.surface,
    borderWidth: 1,
    borderColor: Colours.border,
  },
  optionChipActive: { backgroundColor: Colours.primary, borderColor: Colours.primary },
  optionChipText: { fontSize: FontSize.sm, fontWeight: '700', color: Colours.text },
  optionChipTextActive: { color: Colours.textLight },
  resetButton: {
    marginTop: Spacing.xl,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colours.border,
    alignItems: 'center',
    backgroundColor: Colours.surface,
  },
  resetButtonText: { fontSize: FontSize.md, fontWeight: '800', color: Colours.error },
});
